project:
  type: website  # Defines the project type as a website
  output-dir: website  # Directory where rendered files (HTML, assets) will be placed
  render:
    - website/slides.qmd  # Render Reveal.js slides from this file
    - website/index.qmd  # Render the main website content (if any)
  
  website:
  title: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
  navbar:
    left:
      - href: index.qmd
        text: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
      - text: "Authors"
        href: authors.qmd
      - text: "Data"
        href: data.qmd

output:
  revealjs:
    embed: true  # Embeds all resources (like images, CSS) in the HTML
    output-dir: website  # The Reveal.js slides will be rendered to this directory
