project:
  type: website 
  render:
     - "*.qmd"

website:
  title: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
  navbar:
    left:
      - href: index.qmd
        text: " "
format:
  html:
    theme: lux

