project:
  type: website  # Defines the project type as a website
  render:
     - "*.qmd"

website:
  title: "DSAN 5200"
  navbar:
    left:
      - href: index.qmd
        text: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
      - text: "Data"
        href: data.qmd
format:
  html:
    theme: lux

