project:
  type: website  # Defines the project type as a website
  render:
     - "*.qmd"

website:
  title: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
  navbar:
    left:
      - href: index.qmd
        text: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
      - text: "Authors"
        href: slides.qmd
      - text: "Data"
        href: data.qmd
format:
  html:
    theme: cosmo
    toc: true
