project:
  type: website 
  render:
     - "*.qmd"

website:
  title: "DSAN 5200"
  navbar:
    left:
      - href: index.qmd
        text: "Navigating Change: Analyzing the Evolution of U.S. Manufacturing"
format:
  html:
    theme: lux

